### ISSUE TITLE
dictionaryFile does not work

### ISSUE THREAD

**Issue by FranklinChen** [federkasten/appbundler-plugin#1]
I migrated from `osxappbundle-maven-plugin` but my `dictionaryFile` seems to no longer work.

My `pom.xml` has

```
<dictionaryFile>${basedir}/src/main/app-resources/Info.plist</dictionaryFile>
```

and it used to work, but now I get

```
Could not find resource for template /Users/chen/maven/chatter/src/main/app-resources/Info.plist
```

**Comment by cpesch** [comment]
I've put my custom dictory into src/main/resources/my/Info.plist.template and configured <dictionaryFile>my/Info.plist.template</dictionaryFile>
But I constantly get
[ERROR] Failed to execute goal io.github.appbundler:appbundle-maven-plugin:1.0-SNAPSHOT:bundle (default) on project XXX: Could not find resource for template my/Info.plist.template: Unable to find resource 'my/Info.plist.template' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.github.appbundler:appbundle-maven-plugin:1.0-SNAPSHOT:bundle (default) on project XXX: Could not find resource for template my/Info.plist.template

I've tried to debug it but failed at
                velocity.getEngine().mergeTemplate(dictionaryFile, "UTF-8", velocityContext, writer);

Please help.

**Comment by federkasten** [comment]
@cpesch 

Please run `mvn clean && mvn compile` and check if your `Info.plist.template`  exists in `target/classes`. (perhaps the file located `target/classes/my/Info.plist.template`)

This plugin searches `Info.plist` in `target/classes` and apply Velocity templating.

**Comment by cpesch** [comment]
> dir .\XXX\target\classes\my\Info.plist.template

    Directory: XXX\target\classes\my


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        02.02.2015     09:49       1560 Info.plist.template

As you can see, the file exists. And the error message is still the same: Unable to find resource 'my/Info.plist.template'

Your documentation is pretty clear about this, but it simply doesn't work for me. Is it because I work with Windows and you're using Linux?

**Comment by cpesch** [comment]
[INFO] --- appbundle-maven-plugin:1.0-SNAPSHOT:bundle (default) @ XXXX ---
Checking for additionalBundledClasspathResources: null
Feb 02, 2015 1:14:37 PM org.apache.velocity.runtime.log.JdkLogChute log
INFO: FileResourceLoader : adding path 'target/classes'
[ERROR] ResourceManager : unable to find resource 'my/Info.plist.template' in any resource loader.

**Comment by federkasten** [comment]
OK. I got it.

This cause is Windows. Windows path deliminator is `\`, not `/`.

I will fix soon. Sorry.

**Comment by federkasten** [comment]
@cpesch Probably I fixed with 17897bd. Please re-try.

**Comment by cpesch** [comment]
Thank you for your quick help, but just the path separators don't seem to be the problem:

[INFO] --- appbundle-maven-plugin:1.0-SNAPSHOT:bundle (default) @ XXX ---
Checking for additionalBundledClasspathResources: null
Feb 02, 2015 4:56:02 PM org.apache.velocity.runtime.log.JdkLogChute log
INFO: FileResourceLoader : adding path 'target\classes'
[ERROR] ResourceManager : unable to find resource 'my/Info.plist.template' in any resource loader.

How can I debug where Velocity is searching its templates?

**Comment by cpesch** [comment]
I observed a problem during debugging:

File f = new File(TARGET_CLASS_ROOT, dictionaryFile);

When I call f.getAbsolutePath() it points to the directory of the root pom.xml (XXX\target\classes\my\Info.plist.template) and not the directory of the module XXX\XXX-for-MacOSX\target\classes\my\Info.plist.template. 

When I copy my Info.plist.template to XXX\target\classes\my\Info.plist.template it works.

**Comment by federkasten** [comment]
Thanks for feedback.

I have not checked with sub-moduled maven projects.

Could you create a new issue about it? Because it's getting off this issue.
